# Homepage configuration
# See https://fontawesome.com/v5/search for icons options
title: Dashboard
subtitle: app.jyje.live
logo: assets/icons/pwa-192x192.png
# icon: "fa-solid fa-m" # Optional icon
connectivityCheck: true
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: light # One of 'auto', 'light', or 'dark'
header: true
footer: |
  Since 2024 ⓒ <a href="https://app.jyje.live">app.jyje.live</a>
  with <a href="https://jyje.live">Jeayoung Jeon</a>.
  Powered by <a href="https://github.com/bastienwirtz/homer">Homer</a>.
# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#680C2C"
    highlight-secondary: "#340616"
    highlight-hover: "#680C2C"
    background: "#fafafa"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#680C2C"
    highlight-secondary: "#340616"
    highlight-hover: "#680C2C"
    background: "#212631"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors
  title: NOTICE
  # icon: fa fa-grin
  icon: fas fa-info
  content: |
    This is a collection of applications for my demo cluster. It is not intended for production use.

# Find more information on <a href='https://github.com/bastienwirtz/homer'>github.
# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Dashboard"
    icon: "fas fa-file-alt"
    url: "#"
    # target: "_blank"

  - name: "Stack"
    icon: "fas fa-layer-group"
    url: "#stack"

  - name: "About"
    icon: "fas fa-user-astronaut"
    url: "#about"

  # - name: "Bio"
  #   icon: "fas fa-user-astronaut"
  #   url: "https://jyje.live"

  # - name: "Blog"
  #   icon: "fas fa-pen-to-square"
  #   url: "https://blog.jyje.live"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are opt
services:
  - name: Applications
    icon: fas fa-rocket
    items:
      - name: Grafana
        type: Ping
        logo: https://grafana.com/static/img/menu/grafana2.svg
        subtitle: Cluster monitoring
        tag: "grafana #monitoring #dashboard #plg"
        url: https://grafana.app.jyje.live
      - name: Argo Workflows
        type: Ping
        logo: https://argoproj.github.io/argo-workflows/assets/logo.png
        subtitle: Workflow engine
        tag: "argo-workflows #argo #workflow #pipeline #cicd"
        url: https://workflow.app.jyje.live/workflows
      - name: Ollama WebUI
        type: Ping
        logo: https://ollama.com/public/ollama.png
        subtitle: LLM on Raspberry Pi
        tag: "open-webui #ollama #llm #webui"

  - name: Management
    icon: fas fa-microchip
    items:
      - name: Homer
        type: Ping
        logo: logo.png
        subtitle: This dashboard
        tag: "homer #dashboard #monitoring"
        url: https://app.jyje.live
      - name: Portainer
        # type: Portainer
        # apikey: "ptr_qXkCiCTml2HK0Y9zrtJ2zLj9zVNJxQpnSAlYxjylhJU="
        # environments:
        # - "r4spi-microk8s"
        type: Ping
        logo: https://avatars.githubusercontent.com/u/22225832
        subtitle: Cluster administration
        tag: "portainer #admin #catalog"
        url: "https://portainer.app.jyje.live"
      - name: Argo CD
        type: Ping
        logo: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
        subtitle: App deployment
        tag: "argocd #argo #gitops #cicd"
        url: https://cd.app.jyje.live
      - name: Keycloak
        type: Ping
        logo: https://avatars.githubusercontent.com/u/4921466
        subtitle: Access management
        tag: "keycloak #login #iam #rabc"
        url: https://keycloak.app.jyje.live

  - name: Storage
    icon: fas fa-hdd
    items:
      - name: OpenMediaVault
        type: Ping
        logo: https://avatars.githubusercontent.com/u/1897994
        subtitle: NAS for NFS storage
        tag: "omv #nas #nfs #storage"
        url: https://omv.app.jyje.live
