---
# Additional 'stack' page configuration

# Additional configurations are loaded using its file name, minus the extension, as an anchor (https://<mydashboad>#<config>). 
# `config.yml` is still used as a base configuration, and all values here will overwrite it, so you don't have to re-defined everything

title: Stack

# This overwrites message config. Setting it to empty to remove message from this page and keep it only in the main one:
message: ~

# # as we want to include a differente link here (so we can get back to home page), we need to replicate all links or they will be revome when overwriting the links field:
# links: ~

services:
  - name: Infra
    icon: fas fa-server
    items:
      - name: Raspberry Pi (2x4B, 2x5B)
        logo: https://upload.wikimedia.org/wikipedia/en/c/cb/Raspberry_Pi_Logo.svg
        subtitle: ARM64-based Micro Computers
        tag: "raspi #arm #edge #iot #infra"
        url: https://www.raspberrypi.com

      - name: MicroK8s v1.30
        logo: https://raw.githubusercontent.com/onemarc/tech-icons/main/icons/ubuntu.svg
        subtitle: Lightweight Kubernetes for Edge Devices
        tag: "microk8s #cluster #k8s #canonical #infra"
        url: https://microk8s.io

      - name: Noctua NF-A12x25 PWM
        logo: assets/tools/noctua-logo.png
        subtitle: Silent Fan controlled by Raspberry Pi
        tag: "noctua #cooling #fan #pwm #infra"
        url: https://noctua.at/en/nf-a12x25-pwm

      - name: ipTIME A3004NS-M
        logo: assets/tools/iptime-logo.webp
        subtitle: Home Router for Ingress Traffic
        tag: "iptime #router #network #infra"
        url: https://iptime.com/iptime

  - name: CI/CD
    icon: fas fa-arrows-spin
    items:
      - name: Argo CD
        type: Ping
        logo: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
        subtitle: App deployment
        tag: "argocd #argo #gitops #cicd"
        url: https://cd.app.jyje.online

  - name: Database
    icon: fas fa-database
    items:
      - name: CloudNativePG
        logo: https://cloudnative-pg.io/images/hero_image.svg
        subtitle: PostgreSQL Operator
        tag: "cnpg #operator #dbaas #psql #database"

  - name: Storage
    icon: fas fa-hdd
    items:
      - name: Longhorn
        logo: https://avatars.githubusercontent.com/u/51335366
        subtitle: Block storage for Kubernetes
        tag: "longhorn #storageclass #storage #rancher"
      - name: MinIO
        type: Ping
        logo: https://min.io/resources/img/logo/MINIO_Bird.png
        subtitle: Object storage for Kubernetes
        tag: "minio #operator #dbaas #s3 #storage"
        url: https://minio.app.jyje.online
